export { NewUserDTO } from './new-user.dto';
export { UserUpdateDTO } from './user-update.dto';
export { UserDTO } from './user.dto';
export { ForgotPasswordDTO } from './forgot-password';
export { ChangePasswordRequestIdDTO } from './change-password-request-id.dto';
export { ChangePasswordDTO } from './change-password.dto';
export { NewStudentDTO } from './new-student.dto';
export { SelfUpdateDTO } from './self-update.dto';
export { AdminChangePasswordDTO } from './admin-change-password.dto';