export enum EscolarityEnum {
  ENSINO_FUNDAMENTAL_COMPLETO = 'ENSINO_FUNDAMENTAL_COMPLETO',
  ENSINO_FUNDAMENTAL_INCOMPLETO = 'ENSINO_FUNDAMENTAL_INCOMPLETO',
  ENSINO_FUNDAMENTAL_CURSANDO = 'ENSINO_FUNDAMENTAL_CURSANDO',
  ENSINO_MEDIO_COMPLETO = 'ENSINO_MEDIO_COMPLETO',
  ENSINO_MEDIO_INCOMPLETO = 'ENSINO_MEDIO_INCOMPLETO',
  ENSINO_MEDIO_CURSANDO = 'ENSINO_MEDIO_CURSANDO',
  FACULDADE_COMPLETO = 'FACULDADE_COMPLETO',
  FACULDADE_INCOMPLETO = 'FACULDADE_INCOMPLETO',
  FACULDADE_CURSANDO = 'FACULDADE_CURSANDO',
}
